package com.singularitycoder.viewmodelstuff2.helpers.constants

import com.singularitycoder.viewmodelstuff2.more.model.YoutubeVideo

val animeFightsList = listOf(
    YoutubeVideo(title = "Fate/Apocrypha - Siegfried VS Karna [60FPS]", videoId = "i_kPukc6bkE"),
    YoutubeVideo(title = "Ruler and Lancer of black vs Archer of black", videoId = "JDGR9JIBz-M"),
    YoutubeVideo(title = "Fate/Apocrypha - Ruler and Lancer of black vs Archer of black", videoId = "JDGR9JIBz-M"),
    YoutubeVideo(title = "Fate/Apocrypha - Achilles vs Chiron", videoId = "h_fyu3pwJxY"),
    YoutubeVideo(title = "Shingeki No Kyojin - Eren Rage Mode (Berserk) vs Annie Episode 25", videoId = "w-QxK1I7Va8"),
    YoutubeVideo(title = "Shingeki no Kyojin HD (EPISODE 24) - Eren Titan Transformation vs Annie Scene", videoId = "GLff3_jPZIM"),
    YoutubeVideo(title = "Fog Hill of the Five Elements", videoId = "0OoKXPUvVbo"),
    YoutubeVideo(title = "Fog Hill of the Five Elements (BRIDGE FIGHT SCENE)", videoId = "qZZLkmMeGRY"),
    YoutubeVideo(title = "Fog Hill of the Five Elements - Wu Shan Wu Xing", videoId = "l5k8GjTpa9I"),
    YoutubeVideo(title = "Fog Hill of the Five Elements - Xuan vs Wrath", videoId = "OLo1MOy_6hU"),
    YoutubeVideo(title = "Fog Hill of the Five Elements - Xuan vs Final Form Wrath", videoId = "E475vIKYvD4"),
    YoutubeVideo(title = "Attack on Titan - Eren vs The Armored Titan full fight", videoId = "hyEbggGnT0U"),
    YoutubeVideo(title = "Attack on Titan - Levi vs Kenny Squad - (Full Fight) HD", videoId = "MyJk2YWhfoU"),
    YoutubeVideo(title = "Attack on Titan - Levi vs. The Beast Titan", videoId = "ceQ4nhyuX2k"),
    YoutubeVideo(title = "Attack On Titan - Floch vs ALL (60 fps)", videoId = "hzp1AeiEIMg"),
    YoutubeVideo(title = "Attack On Titan - Eren's first transformation and first fight scenes", videoId = "p2FKMB_sImg"),
    YoutubeVideo(title = "Attack On Titan - Levi vs The Female Titan", videoId = "QMf_Z-Fl7_w"),
    YoutubeVideo(title = "Attack On Titan - Titan Eren vs Female Titan - 60FPS", videoId = "k2u1nTvBYx0"),
    YoutubeVideo(title = "Attack On Titan - Eren vs Warhammer Titan", videoId = "Rv0085ZOIsg"),
    YoutubeVideo(title = "Saber Alter vs Rider - Fate/stay night: Heaven’s Feel lll", videoId = "8W7x_-mMOtU"),
    YoutubeVideo(title = "Saber Alter Excalibur Morgan [4K 60fps]", videoId = "f1JT8z-3cV0"),
    YoutubeVideo(title = "Demon Slayer - Tanjiro Kamado and Tengen Uzui vs Gyutaro", videoId = "GFLVTjAw7Zc"),
    YoutubeVideo(title = "Demon Slayer - Tanjiro Vs Rui Lower Moon", videoId = "VjwU2Xevnx8"),
    YoutubeVideo(title = "Demon Slayer - Rengoku vs Akaza", videoId = "p8uT9y4cPwY"),
    YoutubeVideo(title = "Demon Slayer - Tanjiro Vs Rui", videoId = "NN0f4NyHs40"),
    YoutubeVideo(title = "Boruto - Naruto, Sasuke, and Boruto vs Momoshiki", videoId = "CZJBkQQTiCo"),
    YoutubeVideo(title = "Meliodas vs Ten Commandments", videoId = "92Gvvh0UKjk"),
    YoutubeVideo(title = "Parasyte The Maxim - Fights from anime compilation", videoId = "r_JH_oOkhmk"),
    YoutubeVideo(title = "One Punch Man - Saitama vs Genos Fight | One Punch Man (60FPS)", videoId = "km2OPUctni4"),
    YoutubeVideo(title = "One Punch Man - Saitama vs Boros Fight Full HD", videoId = "ErXfj3sbIfU"),
    YoutubeVideo(title = "Code Geass R2 - Final battle between Kallen and Suzaku", videoId = "9Y44LiqBHsw"),
    YoutubeVideo(title = "Mob Psycho 100 - Shimazaki Fight", videoId = "Ar7fHWRMNoE"),
    YoutubeVideo(title = "Mob Psycho 100 - MOB VS Toichiro Final Fight", videoId = "wRG7Er6qlvk"),
    YoutubeVideo(title = "Mob Psycho 100 - Mob vs Koyama Full Fight (60fps)", videoId = "nJlmcQA_dVQ"),
    YoutubeVideo(title = "Fate/Grand Order-Noble Phantasm's attacking", videoId = "pApAiZymeu0"),
    YoutubeVideo(title = "Kung Fu Panda (2008) - Tai Lung's Escape", videoId = "UsZNj9srzR8"),
    YoutubeVideo(title = "Kung Fu Panda (2008) - Our Battle Will Be Legendary", videoId = "Jy2_J5WCzDY"),
    YoutubeVideo(title = "Kung Fu Panda (2008) - Tai Lung's Revenge Scene", videoId = "GQM4dSjjQuE"),
    YoutubeVideo(title = "Kung Fu Panda (2008) - Fight for the Dragon Scroll", videoId = "AhbCYVILusc"),
    YoutubeVideo(title = "Arcane: League of Legends - All Fight Scenes", videoId = "vnYoxXYZN5g"),
    YoutubeVideo(title = "Gundum Thunderbolt - Snowland Battle", videoId = "wF1dsJnloMo"),
    YoutubeVideo(title = "Gundum Thunderbolt - Full Armor Gundam Io Fleming vs Psycho Zaku Daryl Lorenz", videoId = "dpcruxAuKJU"),
    YoutubeVideo(title = "Gundam 00 - Raiser Battle Scene", videoId = "nYHG_5TVTjU"),
    YoutubeVideo(title = "Megalobox 2 - Fight", videoId = "BYB-o0m5llE"),
    YoutubeVideo(title = "Afro Samurai - first battle (massacre)", videoId = "HykZmVBylrc"),
    YoutubeVideo(title = "Afro Samurai: Resurrection - Bridge Scene", videoId = "RP0yOW6FpEM"),
    YoutubeVideo(title = "Kizumonogatari I: Tekketsu-hen - Koyomi Araragi vs Kiss Shot", videoId = "XCYWiGUXQ-I"),
    YoutubeVideo(title = "Neon Genesis Evangelion - End Of Evangelion - Asuka's Death", videoId = "OO-1Yyi5KPY"),
    YoutubeVideo(title = "Classroom of the elite season 2 episode 12 - Ayanokoji vs Ryuen's group", videoId = "cH249RcbrnM"),
    YoutubeVideo(title = "My Hero Academia - Endeavor Vs Nomu", videoId = "N9UxN1eUfnk"),
    YoutubeVideo(title = "My Hero Academia - Deku vs Todoroki", videoId = "wpOhT35YtWg"),
    YoutubeVideo(title = "Fire Force - Shinra vs Sho Kusakabe [DUBBED]", videoId = "ZYlp58Mjpxc"),
).shuffled()

// Absolutely every OST in Fate/Apocrypha is amazing. Kudos to Masaru Yokoyama
val animeMusicList = listOf(
    YoutubeVideo(title = "Sirius the Jaeger - Definition of Fate", videoId = "3bhJ3DC789g"),
    YoutubeVideo(title = "Sirius the Jaeger - Rare Occasions", videoId = "JdNB9sCQ_fo"),
    YoutubeVideo(title = "Fate/Apocrypha - Fate/Apocrypha", videoId = "Ql42kdD-KlQ"),
    YoutubeVideo(title = "Fate/Apocrypha - Confronting", videoId = "uuxfvgXReVc"),
    YoutubeVideo(title = "Fate/Apocrypha - The knight of rebelion", videoId = "yprW-4ie-gk"),
    YoutubeVideo(title = "Fate/Apocrypha - Invasion", videoId = "ORoHW9zGdI8"),
    YoutubeVideo(title = "Fate/Apocrypha - Savior", videoId = "KlNYFPOetpE"),
    YoutubeVideo(title = "Fate/Apocrypha - Amakusa Shirou Tokisada", videoId = "0F1ZyyqxhH0"),
    YoutubeVideo(title = "Fate/Apocrypha - The Great Holy Grail War", videoId = "ZOzuV2W0ZWU"),
    YoutubeVideo(title = "Fate/Apocrypha - La Pucelle", videoId = "RqUE8r-hJBU"),
    YoutubeVideo(title = "Fate/Apocrypha - Love", videoId = "Njua-wiQKFE"),
    YoutubeVideo(title = "Fate/Apocrypha - Thoughts flows on", videoId = "2ki9W4hjnog"),
    YoutubeVideo(title = "Fate/Apocrypha - Ruler: Prayer", videoId = "Nlx1_GzFVWA"),
    YoutubeVideo(title = "Fate/Apocrypha - Ruler: Execution", videoId = "ud9vdD7UX2Q"),
    YoutubeVideo(title = "Fate/Apocrypha - Battle", videoId = "V3646EiXljc"),
    YoutubeVideo(title = "Fate/Apocrypha - Grand War", videoId = "NLW9WkX38Wc"),
    YoutubeVideo(title = "Fate/Apocrypha - Battle: Red Faction", videoId = "EiDzO5zvyFs"),
    YoutubeVideo(title = "Fate/Apocrypha - Rising", videoId = "8deiDDhqVMk"),
    YoutubeVideo(title = "Fate/Apocrypha - Before Dawn", videoId = "0EnTiSG8vcg"),
    YoutubeVideo(title = "Fate/Apocrypha - Freedom", videoId = "Ii1fEBLbiaw"),
    YoutubeVideo(title = "Fate/Apocrypha - Affection", videoId = "aI5jHIwMSJ0"),
    YoutubeVideo(title = "Fate/Apocrypha - Sieg: Alive", videoId = "Noy_NieI0Gc"),
    YoutubeVideo(title = "Fate/Apocrypha - In the Dream", videoId = "lIjrk76k1Ao"),
    YoutubeVideo(title = "Fate/Apocrypha - Insanity of Dominator", videoId = "uPM3CONLfjI"),
    YoutubeVideo(title = "Fate/Apocrypha - Glory of the King", videoId = "mMexy1uu7HM"),
    YoutubeVideo(title = "Fate/Apocrypha - Intensity of Lord", videoId = "w4XdHnAETDU"),
    YoutubeVideo(title = "Fate/Apocrypha - Say Goodbye", videoId = "V8tviWes0nM"),
    YoutubeVideo(title = "Fate/Apocrypha - Requiem", videoId = "2hZ6G1vVZwM"),
    YoutubeVideo(title = "Fate/Apocrypha - Sieg: Will", videoId = "NqOJUy98hX0"),
    YoutubeVideo(title = "Fate/Apocrypha - Sieg: Despair", videoId = "Mnuhq6n5_XU"),
    YoutubeVideo(title = "Fate/Apocrypha - Fearless Smile", videoId = "b46HzltbbSg"),
    YoutubeVideo(title = "Fate/Apocrypha - Apocrypha", videoId = "ibXmpHqarPw"),
    YoutubeVideo(title = "Fate/Apocrypha - Bloody Soul", videoId = "8CvRkGgITjA"),
    YoutubeVideo(title = "Fate/Apocrypha - Afterglow", videoId = "H1tVYKwoQ30"),
    YoutubeVideo(title = "Fate/Apocrypha - Justeaze", videoId = "zA4abm6D5NY"),
    YoutubeVideo(title = "Gundam Unicorn - 1ST MOV. :BANSHEE", videoId = "BUXh_AQ5xvI"),
    YoutubeVideo(title = "Gundam Unicorn - MAD-NUG", videoId = "ZcLoj0qoe_g"),
    YoutubeVideo(title = "Gundam Unicorn - MOBILE SUIT ＜W-REC MIX＞", videoId = "6Z1e-3dPiTk"),
    YoutubeVideo(title = "Gundam Unicorn - U.C.0096", videoId = "xMMIiuefw8k"),
    YoutubeVideo(title = "Gundam Unicorn - UNICORN", videoId = "hAqqAwhfet8"),
    YoutubeVideo(title = "Gundam Unicorn - MOBILE SUIT", videoId = "afuVyoW15HM"),
    YoutubeVideo(title = "Gundam Unicorn - LAPLACE", videoId = "fWjLln3W2xI"),
    YoutubeVideo(title = "Gundam Unicorn - FULL-FRONTAL", videoId = "xnx2WLiLrDM"),
    YoutubeVideo(title = "Gundam Unicorn - LIFE & DEATH", videoId = "s5UgiiI9u84"),
    YoutubeVideo(title = "Gundam Unicorn - RX-0", videoId = "bokihr6DzIw"),
    YoutubeVideo(title = "Gundam Unicorn - ZERO GRAVITY", videoId = "rq2qiODoKus"),
    YoutubeVideo(title = "Gundam Unicorn - 2ND MOV. :PSYCHO-FIELD", videoId = "9uP_sNt5QGw"),
    YoutubeVideo(title = "Gundam Unicorn - 3RD MOV. :ANGELO", videoId = "E7AqQLhQgdQ"),
    YoutubeVideo(title = "Gundam Unicorn - 5TH MOV. :GUNDAM", videoId = "IbyeO2nkm9I"),
    YoutubeVideo(title = "Gundam Unicorn - 1stMob. :2009522or0311", videoId = "HL78LkCCGcg"),
    YoutubeVideo(title = "Gundam Unicorn - 2ndMob. :MSGUCEP7", videoId = "M5kv6tHHkIQ"),
    YoutubeVideo(title = "Gundam Unicorn - 6thMob. :UNICORN GUNDAM", videoId = "4TgW2Lq9Wv8"),
    YoutubeVideo(title = "Gundam Unicorn - 8thMob. :BEGINNING ＜ORCH-VER＞", videoId = "KyCuNKwxwlo"),
    YoutubeVideo(title = "ALDNOAH.ZERO - R0B0T", videoId = "NSxrBYCUkb8"), // A  W  E  S  O  M  E
    YoutubeVideo(title = "ALDNOAH.ZERO - Firestar", videoId = "P_QIThn4clw"),
    YoutubeVideo(title = "ALDNOAH.ZERO - AZPV", videoId = "QofZKy9V31U"),
    YoutubeVideo(title = "ALDNOAH.ZERO - A-0picturez", videoId = "yrqi546J7hA"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Mkaliez", videoId = "ZmbUxjXLSdE"),
    YoutubeVideo(title = "ALDNOAH.ZERO - 2Zero14Zero91Zero", videoId = "ofxC68IItCA"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Az-Kat", videoId = "BmKJNDTW1Ps"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Ad2014-7.5/7.9-Zero.A", videoId = "70o5KM87jGY"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Alc-@", videoId = "CzPH-UpXrYU"),
    YoutubeVideo(title = "ALDNOAH.ZERO - AcyOrt", videoId = "1K_h3p4uLQ0"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Kanascene", videoId = "nRvMDb5_zzA"),
    YoutubeVideo(title = "ALDNOAH.ZERO - +61Yard", videoId = "5-vaaNipc4g"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Ver$", videoId = "kTfztbKqVNE"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Site-N0W1", videoId = "YHYjQdP4Txc"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Ch19woFirestar", videoId = "F-PkhV4ng04"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Al-Door0", videoId = "XHr5waMFQL8"),
    YoutubeVideo(title = "ALDNOAH.ZERO - Az-17ho", videoId = "UEgm4cWDZ9E"),
    YoutubeVideo(title = "Sawano Hiroyuki - Kiryu G@ Ki Ll", videoId = "VTiYdpeHIv4"),
    YoutubeVideo(title = "Sawano Hiroyuki - Gorilla Ja L", videoId = "z3V7__7-jLM"),
    YoutubeVideo(title = "Sawano Hiroyuki - Nui Harime's theme", videoId = "1zAMJXZnJoY"),
    YoutubeVideo(title = "Sawano Hiroyuki - Blumenkranz", videoId = "zRI5uW6DLXg"),
    YoutubeVideo(title = "Sawano Hiroyuki - K1llwaill", videoId = "VSopu4EecMo"),
    YoutubeVideo(title = "Sawano Hiroyuki - Ki LLL A Iki Ll", videoId = "pyePOjwZa2k"),
    YoutubeVideo(title = "Sawano Hiroyuki - Kiryu Ha Ki Ll", videoId = "0hN3NzYCCSU"),
    YoutubeVideo(title = "Sawano Hiroyuki - Ki Ru A Kill", videoId = "7mEXvNuoKIA"),
    YoutubeVideo(title = "Sawano Hiroyuki - Rhythm Kyoukagata Futatsuboshi Gokuseifuku", videoId = "7mEXvNuoKIA"),
    YoutubeVideo(title = "Sawano Hiroyuki - Naming Sence 0Gata Itsutsuboshi Gokuseifuku", videoId = "MFvSobbEG0Q"),
    YoutubeVideo(title = "Sawano Hiroyuki - Tsuika Hacchugata Mutsuboshi Gokuseifuku", videoId = "3EHTL4d2Ags"),
    YoutubeVideo(title = "Sawano Hiroyuki - Mt Hensougata Yatsuboshi Gokuseifuku", videoId = "IaOUKMglilI"),
    YoutubeVideo(title = "Sawano Hiroyuki - Tabun Lasu Bossgata Kokonotsuboshi Gokuseifuku", videoId = "qVUIrvSdt4Y"),
    YoutubeVideo(title = "Sawano Hiroyuki - Zenhan Saisyurokugata Tohnohoshi Gokuseifuku", videoId = "9qurFQeGAew"),
    YoutubeVideo(title = "Sawano Hiroyuki - Tsuika Saisyurokugata Tohtohitotsuboshi Gokuseifuku", videoId = "0kPXa5REmzc"),
    YoutubeVideo(title = "Sawano Hiroyuki - Juyobutsu Hakko Kyouchogata Tohtofutatsuboshi Gokuseifuku", videoId = "o6g6tqiYauo"),
    YoutubeVideo(title = "Solo Leveling - Official Trailer", videoId = "Ls3Eorw10uU"),
    YoutubeVideo(title = "Sawano Hiroyuki Playlist - Avid, Tranquility, CRY, CRYst-Alise, e of s, ViEW, narrative, ninelie ＜cry-v＞, Binary Star, Unti-L, Cage, 0.vers, oldToday, mot1on, No differences, Till I, scaPEGoat", videoId = "PUSkqc1amgI"),
    YoutubeVideo(title = "Sawano Hiroyuki 2nd Playlist", videoId = "388h287dOWc"),
    YoutubeVideo(title = "Ost Anne Happy - Michino Timothy Kimino Kimochi", videoId = "815kbvmNWNM"),
    YoutubeVideo(title = "Aimer - Am02:00", videoId = "-Hn6O-WvD7o"),
    YoutubeVideo(title = "Aimer - Even Heaven", videoId = "BOGoJYZWmuk"),
    YoutubeVideo(title = "Aimer - Re I Am", videoId = "YyZdbDEgK50"),
    YoutubeVideo(title = "Aimer - StarRingChild", videoId = "cmXW3qfhT60"),
    YoutubeVideo(title = "Aimer - Higher Ground", videoId = "w_FeX0Z8JAo"),
    YoutubeVideo(title = "Aimer - Kyoukara Omoide", videoId = "ImRjy0vgYoI"),
    YoutubeVideo(title = "Aimer - Koi wa Ameagari no You ni - Ref:rain", videoId = "7CG2qA_IbAs"),
    YoutubeVideo(title = "Aimer - After Dark - Polaris", videoId = "NJkQzZOdOsI"),
    YoutubeVideo(title = "Aimer - Natsume's Book of Friends - Akane Sasu", videoId = "tKUC6vqC1kw"),
    YoutubeVideo(title = "Aimer - Kataomoi(Unrequited Love)", videoId = "F_62fr-I3E4"),
    YoutubeVideo(title = "Attack on Titan - Best of Soundtracks", videoId = "ZUj6k5LQrJ0"),
    YoutubeVideo(title = "Attack on Titan - Reiner and Bertholdt's Transformation Theme", videoId = "rdml5r6Y_g4"),
    YoutubeVideo(title = "The Seven Deadly Sins - Here Comes The Jikkai · KOHTA YAMAMOTO", videoId = "VMZTkvnRUPE"), // Too many favorites - https://www.youtube.com/watch?v=HxlysqrFjHo&list=PLvXMARe51eebmg3Xf4wIeeLtFkafv0fh8
    YoutubeVideo(title = "The Seven Deadly Sins - Suite-2Gakusyou", videoId = "YZEzhBBuf7E"),
    YoutubeVideo(title = "Berserk - Son Cauchemar - Shiro Sagisu", videoId = "FNC-M9279jE"),
    YoutubeVideo(title = "Berserk Golden Age - Hundred Years War", videoId = "OG8GxzJTBck"),
    YoutubeVideo(title = "Kenji Kawai Cinema Symphony Ghost In The Shell", videoId = "WjOuEruzoh0"),
    YoutubeVideo(title = "Made In Abyss - Tomorrow", videoId = "BeSbmS06k1k"),
    YoutubeVideo(title = "Tower of God - Irregular God", videoId = "ENCJrayjnjE"),
    YoutubeVideo(title = "Tower of God - Alita", videoId = "elGoXAIsddM"),
    YoutubeVideo(title = "Tower of God - Berserker Bam", videoId = "BNZerdoRl_Q"),
    YoutubeVideo(title = "Megalo Box - MEGALOBOX", videoId = "Pxg9s9OD-qU"),
    YoutubeVideo(title = "Megalo Box - Enter The Arena", videoId = "rqUCKw13D0Y"),
    YoutubeVideo(title = "Megalo Box - The theme of the NOMAD", videoId = "mft3q1Y71HM"),
    YoutubeVideo(title = "Megalo Box - Determination", videoId = "NbM5PJ1FtFE"),
    YoutubeVideo(title = "Megalo Box - The theme of Mac", videoId = "1GMpUFrLL-M"),
    YoutubeVideo(title = "Uchouten Kazoku - Kakusanakute mo li ja nai ka", videoId = "thiLdlj0Oqk"),
    YoutubeVideo(title = "Uchouten Kazoku - Suibun Okiniiri no You desu", videoId = "RJFwlHyGAsc"),
    YoutubeVideo(title = "Uchouten Kazoku - Ebisugawa no Musume, Kaisei", videoId = "xplxAEr0xG0"),
    YoutubeVideo(title = "Uchouten Kazoku - Hodo Hodo no Eikou are", videoId = "mIjOgDMpMkU"),
    YoutubeVideo(title = "Uchouten Kazoku - Que Sera Sera (TV Size)", videoId = "9v2DACnQ7KE"),
    YoutubeVideo(title = "Your Name - Sparkle - Movie Ver", videoId = "a2GujJZfXpg"),
    YoutubeVideo(title = "Your Name - Sparkle", videoId = "-pHfPJGatgE"),
    YoutubeVideo(title = "Your Name - Nandemonaiya - Movie Ver", videoId = "n89SKAymNfA"),
    YoutubeVideo(title = "Death Note - Kyrie, Kyrie II And Kyrie Orchestra", videoId = "UaIoK3Bf6lk"),
    YoutubeVideo(title = "Death Note - Senritsu", videoId = "-IRRlCOmUR8"),
    YoutubeVideo(title = "Mobile Suit Gundam 00 ED2 - Friends", videoId = "nD9LwQHc1ik"),
    YoutubeVideo(title = "Mobile Suit Gundam 00 ED4 - Trust You", videoId = "j8aecF5HXm4"),
    YoutubeVideo(title = "Mobile Suit Gundam 00 ED4 - Trust You - Video", videoId = "uORNCAyviK4"),
    YoutubeVideo(title = "Tokyo Ghoul - White Silence", videoId = "BkrICLDQ3T4"),
    YoutubeVideo(title = "Sayuri - Bake a Cake", videoId = "SLHHvR1Iss4"),
    YoutubeVideo(title = "Erased : 01 - Only I am missing", videoId = "xc74Bm__cP8"),
).shuffled()

val epicAnimeMomentsList = listOf(
    YoutubeVideo(title = "Code Geass, Best Anime Ever, Ending! 1080p", videoId = "rS-FBuWG_zQ"),
    YoutubeVideo(title = "Code Geass R2 - Lelouch Takes Over the World", videoId = "xnFdY7168DY"),
    YoutubeVideo(title = "Attack On Titan - Eren vs Annie - Eren Transforms in the forest", videoId = "BPohSG4ZNes"),
    YoutubeVideo(title = "Attack on Titan - The Owl", videoId = "gLtky3DaBO0"),
    YoutubeVideo(title = "Attack on Titan - Colossal & Armored Titan REVEALED", videoId = "3v_561hRxs4"),
    YoutubeVideo(title = "Attack on Titan - Annie Leonhardt/Female Titan - Powers & Fight Scenes (AOT)", videoId = "IZdNJJueKfU"),
    YoutubeVideo(title = "Kizumonogatari Part 2: Nekketsu - Koyomi Araragi vs. Guillotine Cutter", videoId = "yl7ldmQPwIM"),
    YoutubeVideo(title = "The Rumbling arrives on Marley - Eren Founding Titan | Attack on Titan Season 4 Part 2 EP 12 FINAL", videoId = "wT2H68kEmi8"),
    YoutubeVideo(title = "Shingeki no Kyojin - Eren blocks gate with boulder", videoId = "iaLJ1Jk35lU"),
    YoutubeVideo(title = "Shingeki no Kyojin - Eren Transforms - Willy Tybur Speech: The Final Season", videoId = "pR3KdTbbBoM"),
    YoutubeVideo(title = "Monster - Tenma confronts Johan", videoId = "NMZVAN3UUmg"),
    YoutubeVideo(title = "Haikyuu - Oikawa’s DIABOLICAL SERVE", videoId = "FpCm7fV-LSY"),
    YoutubeVideo(title = "Haikyuu - Oikawa Super Long Set to Iwaizumi against Karasuno", videoId = "fVyGOb4FcV8"),
    YoutubeVideo(title = "Redline - Intro - First Yellowline Race HD", videoId = "rRLPdgcGPRg"),
).shuffled()

// King Arthur's OSTs are just a work of art. Super creative. Again every OST is good.
val otherMusicList = listOf(
    YoutubeVideo(title = "Pandit Jasraj - Vraje Vasantam", videoId = "ItAnTZjopAM"),
    YoutubeVideo(title = "GN Balasubramaniam - Live Concert - Yochana kamala lochana", videoId = "S6bx-zWnuwI"),
    YoutubeVideo(title = "GN Balasubramaniam - Manasu Swadhina", videoId = "IA5Oa6VJAyk"),
    YoutubeVideo(title = "GN Balasubramaniam - Raga Tana Pallavi - Raga Shanmukhapriya", videoId = "h3SINDPqtEg"),
    YoutubeVideo(title = "GN Balasubramaniam - RTP SHANMUKHAPRIYA", videoId = "SjwTTnK1ha0"),
    YoutubeVideo(title = "GN Balasubramaniam - Saketa Nagara ~ Harikambhoji", videoId = "Q1rQMuhxhtQ"),
    YoutubeVideo(title = "GN Balasubramaniam - Saketha Nagra Nadha", videoId = "0ptGsgILmPU"),
    YoutubeVideo(title = "GN Balasubramaniam - Brochevarevarura (Full 36 min version)", videoId = "VqVb0xmEGFQ"),
    YoutubeVideo(title = "GN Balasubramaniam - T Chowdiah - C S Murugabhoopathi - Bangalore 01 04 1957", videoId = "HdFbJip5Two"),
    YoutubeVideo(title = "GN Balasubramaniam - The Music Academy, Madras, 29.12.1964", videoId = "aecqfKBbEpo"),
    YoutubeVideo(title = "GN Balasubramaniam - Sarasa sama dana - Raga Kapi Narayani", videoId = "kH8FzH-0LzA"),
    YoutubeVideo(title = "GN Balasubramaniam - Sarasa sama dana - Followed by Thani - Palghat R Raghu", videoId = "Vc9se45wIaE"),  // A truly fun song
    YoutubeVideo(title = "GN Balasubramaniam - Raga sudharasa panamu - AndolikA - Tyagaraja", videoId = "8vqgtNKQ4yg"),
    YoutubeVideo(title = "GN Balasubramaniam - Pari Palayamam", videoId = "cV3P617hxQk"), // King of Carnatic. Period.
    YoutubeVideo(title = "GN Balasubramaniam - Vasudevayani", videoId = "BmsIChomCTg"),
    YoutubeVideo(title = "GN Balasubramaniam - Sama Gana Priye", videoId = "cQ6Am4Sv58I"),
    YoutubeVideo(title = "GN Balasubramaniam - Vararagalaya - Chenchukamboji - Adi", videoId = "Lwfd4QeF1BY"),
    YoutubeVideo(title = "GN Balasubramaniam - Swaminatha Paripalaya", videoId = "j1t8BYA7CvQ"),
    YoutubeVideo(title = "GN Balasubramaniam - Madhyamavathi - Palinchu Kamakshi Parvati", videoId = "BgwDBJsgGuE"), // Not sure if anybody in the current generation can sing this the way GNB did. Simply super human.
    YoutubeVideo(title = "GN Balasubramaniam - MSG, CSM, RTP, Nattakurinji - Koniyada Tharama Nee Mahima - Adi - Tisra Gathi", videoId = "zpT8NmpGgw8"), // Not sure if anybody in the current generation can sing this the way GNB did. Simply super human.
    YoutubeVideo(title = "GN Balasubramaniam - Carnatic Vocal (1910 -1965) | Jukebox", videoId = "bgEpgmEitOs"),
    YoutubeVideo(title = "GN Balasubramaniam - Nenarunchinanu - Malavi - Tyagaraja", videoId = "nJXVIotYJPI"), // One of my favs
    YoutubeVideo(title = "GN Balasubramaniam - Nidhi cala sukhama - Kalyani - Tyagaraja", videoId = "yZGIJqqliUg"),
    YoutubeVideo(title = "GN Balasubramaniam - Evari bodhanavini - Varnam Abhogi", videoId = "6dJIRdvpv_o"),
    YoutubeVideo(title = "GN Balasubramaniam - Vasudevayani - Kalyani", videoId = "00paqrAzlfw"),
    YoutubeVideo(title = "GN Balasubramaniam - Kalayami - Begada - Misra Chapu (Live)", videoId = "CWMdH7dOLeY"),
    YoutubeVideo(title = "GN Balasubramaniam - Valachi vachchiyunna napai chalamu - Ragamalika", videoId = "FHVu3VURnsQ"),
    YoutubeVideo(title = "GN Balasubramaniam - Kalayami - Begada - Misra Chapu", videoId = "CWMdH7dOLeY"),
    YoutubeVideo(title = "Parur Sundaram Iyer & MSG_Manavyala", videoId = "823uFFoaLGc"),
    YoutubeVideo(title = "MS Gopalakrishnan- Violin - Manavyalakinchara", videoId = "m7lKOttZR7g"),
    YoutubeVideo(title = "Madurai Mani Iyer - Brochevarevarura", videoId = "lgdwg2KmjN4"),
    YoutubeVideo(title = "Madurai Mani Iyer - Rama nee Samana - Kharaharapriya", videoId = "xjnqcwR4EhM"),
    YoutubeVideo(title = "Madurai Mani Iyer - Chakkani Rajamargamu - Kharaharapriya", videoId = "HVMHQtdW4U8"),
    YoutubeVideo(title = "Ranjani & Gayatri - Mysuru Asthana Sangeetothsava - Karnatic Vocal Concert", videoId = "cU9YmKmOfD8"),
    YoutubeVideo(title = "TM Krishna - Ragam Neelambari", videoId = "ovgWK5aQcpM"),
    YoutubeVideo(title = "TM Krishna - Manavyalakinchara, Tyagaraja Smaranotsava Sabha Nellore", videoId = "ovgWK5aQcpM"),
    YoutubeVideo(title = "TM Krishna - Ragam Nalinakanthi", videoId = "5yZEsJDJ9yc"),
    YoutubeVideo(title = "TM Krishna - Amba Neelayataakshi - Neelambari - Adi - Mutthuswamy Deekshitar", videoId = "Z6bGA61mOi4"),
    YoutubeVideo(title = "Sanjay Subrahmanyan - Raga Nattakurinji", videoId = "3D6RjQAR1yU"),
    YoutubeVideo(title = "Lalgudi Jayaram - Valachi", videoId = "OumVYIf5dzY"),
    YoutubeVideo(title = "Sahana - Pearls of compassion", videoId = "wKMqG8MYWL4"),
    YoutubeVideo(title = "Ramnad Krishnan - RTP - bhairavi - Cetah Sri Raman Cintaya jimuta Syamam", videoId = "bqGa_hJBUNE"),
    YoutubeVideo(title = "Ramnad Krishnan - Raghupate Rama - Sahana - Thyagaraja", videoId = "KenvJC9B5WU"),
    YoutubeVideo(title = "E.S.Posthumus - Nasivern Pi", videoId = "sHPZ9eQrHeE"), // Absolutely Incredible. Almost every sound track is great. https://www.youtube.com/channel/UCvJKyvGIe7VpfBDpkHOMfOw
    YoutubeVideo(title = "E.S.Posthumus - Pompeii", videoId = "1lwl9ZHklLY"),
    YoutubeVideo(title = "E.S.Posthumus - Unstoppable", videoId = "uFZSh6MSXno"),
    YoutubeVideo(title = "E.S.Posthumus - Arise", videoId = "NYcHp_3sfMs"),
    YoutubeVideo(title = "E.S.Posthumus - Cuzco", videoId = "SzbEyBxIHFg"),
    YoutubeVideo(title = "E.S.Posthumus - Nara", videoId = "HhBHSvxi25k"),
    YoutubeVideo(title = "Carl Orff - O Fortuna ~ Carmina Burana", videoId = "GXFSK0ogeg4"),
    YoutubeVideo(title = "Two steps from Hell - Heart of Courage", videoId = "K2iC1aCPbKA"), // Again lots of great stuff — https://www.youtube.com/channel/UC3swwxiALG5c0Tvom83tPGg
    YoutubeVideo(title = "King Arthur - The Devil and The Huntsman", videoId = "yGnfFW-vyzU"),
    YoutubeVideo(title = "King Arthur - The Devil & The Daughter Bonus Track", videoId = "XTLfmMyRKYo"),
    YoutubeVideo(title = "King Arthur - The Darklands", videoId = "WkNYkwMbl0U"),
    YoutubeVideo(title = "King Arthur - The Lady In The Lake", videoId = "ewSjRtNJ7W8"),
    YoutubeVideo(title = "King Arthur - Riot & Flames Bonus Track", videoId = "ZNGqIEIGrYE"),
    YoutubeVideo(title = "King Arthur - Assassins Breathe", videoId = "1oaxmVk8ir8"),
    YoutubeVideo(title = "King Arthur - Growing Up Londinium", videoId = "e2LLS33eQvk"),
    YoutubeVideo(title = "King Arthur - From Nothing Comes A King", videoId = "U5hE3GLSnTo"),
    YoutubeVideo(title = "King Arthur - Legend Of The Sword", videoId = "QjWDBEz_6p4"),
    YoutubeVideo(title = "King Arthur - Jackseye's Tale", videoId = "ApvDXCluFSc"),
    YoutubeVideo(title = "King Arthur - The Story Of Mordred", videoId = "Fmm1btzQf9M"),
    YoutubeVideo(title = "King Arthur - The Legend Of Excalibur", videoId = "lw0TGTxqtZU"),
    YoutubeVideo(title = "King Arthur - Seasoned Oak", videoId = "JGV95hAHqqs"),
    YoutubeVideo(title = "King Arthur - The Power Of Excalibur", videoId = "fFTtUrXPBqk"),
    YoutubeVideo(title = "King Arthur - The Vikings & The Barons", videoId = "7obz77H_YN4"),
    YoutubeVideo(title = "King Arthur - The Politics & The Life", videoId = "56cnOkQFRwo"),
    YoutubeVideo(title = "King Arthur - Tower & Power", videoId = "xNTuhoHKts4"),
    YoutubeVideo(title = "King Arthur - The Born King", videoId = "FRZPqunSnNg"),
    YoutubeVideo(title = "King Arthur - Run Londinium", videoId = "OLVtqVxZgYI"),
    YoutubeVideo(title = "King Arthur - Fireball", videoId = "DRNhJyoD128"),
    YoutubeVideo(title = "King Arthur - Journey To The Caves", videoId = "tX9VKlL-yOk"),
    YoutubeVideo(title = "King Arthur - The Wolf & The Hanged Men", videoId = "m7LzDCyb9yY"),
    YoutubeVideo(title = "King Arthur - Revelation", videoId = "EaY3nuRvdqk"),
    YoutubeVideo(title = "King Arthur - Destiny Of The Sword", videoId = "VQH-LWB1Jnc"),
    YoutubeVideo(title = "King Arthur - Knights Of The Round Table", videoId = "HxxzLygGLQ0"),
    YoutubeVideo(title = "King Arthur - The Coronation", videoId = "AsCvIT2t_RU"),
    YoutubeVideo(title = "King Arthur - The Ballad Of Londinium Bonus Track", videoId = "iAfKL6XbrdE"),
    YoutubeVideo(title = "King Arthur - Anger Bonus Track", videoId = "O8aRJpaPH0U"),
    YoutubeVideo(title = "King Arthur - Cave Fight Bonus Track", videoId = "67o8mFU7t2w"),
    YoutubeVideo(title = "King Arthur - Confrontation With The Common Man Bonus Track", videoId = "B4k1A3_GOIs"),
    YoutubeVideo(title = "Rok Nardin & Samuel Kim - Chaos", videoId = "3cKUsS67rOc"),
    YoutubeVideo(title = "X-Men: First Class - Frankenstein's Monster", videoId = "diMNV6A3_x0"),
    YoutubeVideo(title = "X-Men: First Class - First Class", videoId = "b_zN9VsPffY"),
    YoutubeVideo(title = "X-Men: First Class - Magneto", videoId = "zFmBIRS7yoU"),
    YoutubeVideo(title = "X-Men: First Class - Sub Lift", videoId = "vYFxv8rQOCQ"),
    YoutubeVideo(title = "James Brown - I Got The Feelin' (Extended Version)", videoId = "Cda0twzCMC4"),
    YoutubeVideo(title = "James Brown - People Get Up And Drive Your Funky Soul (Remix)", videoId = "Nl-RVIdTUVI"),
    YoutubeVideo(title = "James Brown - Ain't It Funky Now (Live At The Olympia, Paris / 1971)", videoId = "NKloz_wR6n4"),
    YoutubeVideo(title = "James Brown - Sunny (Live At The Olympia, Paris / 1971)", videoId = "cNFb7vfANVE"),
    YoutubeVideo(title = "James Brown - Get Up Offa That Thing (Release The Pressure)", videoId = "QS8FxHsw0U0"),
    YoutubeVideo(title = "James Brown - Papa Don't Take No Mess", videoId = "T0QQUps8954"),
    YoutubeVideo(title = "James Brown - Mind Power", videoId = "7naR12OPxRw"),
    YoutubeVideo(title = "James Brown - Super Bad, Pts. 1, 2 & 3 (Mono Version)", videoId = "u4ePdvrp9go"),
    YoutubeVideo(title = "James Brown - The Payback", videoId = "D7ks03zsg1o"),
    YoutubeVideo(title = "James Brown - Cold Sweat", videoId = "lSh-QQuW3lU"),
    YoutubeVideo(title = "James Brown - Papa's Got A Brand New Bag", videoId = "M7DNkovC2Tk"),
    YoutubeVideo(title = "James Brown - Your Cheatin' Heart", videoId = "fGY9i61XhEg"),
    YoutubeVideo(title = "James Brown - Money Won't Change You", videoId = "8tJ6HyUmjqk"),
    YoutubeVideo(title = "James Brown - Get It Together (Boston) 1968", videoId = "RnO8sHmkbv4"),
    YoutubeVideo(title = "James Brown - I Got The Feeling - Live At The Boston Garden (1968)", videoId = "n0rOo8bX6P8"),
    YoutubeVideo(title = "James Brown - Gonna Have A Funky Good Time", videoId = "P6iSL1dsShc"),
    YoutubeVideo(title = "James Brown - Funky Drummer (Pt. 1 & 2)", videoId = "QXw6YZltKJk"),
    YoutubeVideo(title = "James Brown - Funky Drummer (Bonus Beat Reprise)", videoId = "7dtpj8qa1hQ"),
    YoutubeVideo(title = "James Brown - Out of Sight", videoId = "7PtI_xVfuUM"),
    YoutubeVideo(title = "Otis Redding - Papas Got a Brand New Bag Live", videoId = "-LmfX4Yo0Hs"),
    YoutubeVideo(title = "Lamb of God - Again We Rise", videoId = "Xe07zUkryeI"),
    YoutubeVideo(title = "Lamb of God - Walk with Me In Hell", videoId = "m4QyQk8vOCY"),
    YoutubeVideo(title = "Lamb of God - Ashes of the Wake", videoId = "PJcy3VQJA6o"),
    YoutubeVideo(title = "Lamb of God - Omerta", videoId = "-xYZM04JxnQ"),
    YoutubeVideo(title = "Lamb of God - The Faded Line", videoId = "JuRRnVqv2Vc"),
    YoutubeVideo(title = "Lamb of God - 11th Hour", videoId = "beltaLLilj4"),
    YoutubeVideo(title = "Lamb of God - Descending", videoId = "_V_ZbJE5oLs"),
    YoutubeVideo(title = "Lamb of God - Blacken the Cursed Sun", videoId = "_oGY68hJbs4"),
    YoutubeVideo(title = "Lamb of God - As the Palaces Burn", videoId = "eWVrdFrpXHE"),
    YoutubeVideo(title = "Louis Armstrong - What A Wonderful World (Lyrics)", videoId = "A3yCcXgbKrE"),
    YoutubeVideo(title = "Coldplay - Up&Up", videoId = "BPNTC7uZYrI"),
    YoutubeVideo(title = "Coldplay - The Scientist", videoId = "RB-RcX5DS5A"),
    YoutubeVideo(title = "André Rieu - The Beautiful Blue Danube", videoId = "IDaJ7rFg66A"),
    YoutubeVideo(title = "Yanni - Prelude and Nostalgia", videoId = "tKVzm0SBYtQ"),
    YoutubeVideo(title = "Yanni - Into The Deep Blue", videoId = "t5dOFdllgnM"),
    YoutubeVideo(title = "Kyrie: Orbis Factor, medieval chant of the Gradual of Eleanor of Brittany", videoId = "E8Mf-1A6YtE"),
    YoutubeVideo(title = "Roman Kim - W.A.Mozart-Eine kleine Nachtmusik [Violin Solo]", videoId = "KsxY3WL1cP8"),
    YoutubeVideo(title = "Bijan Mortazavi 1994 Dance of Fire (Concert)", videoId = "HoCe3mmb4nc"),
    YoutubeVideo(title = "Craig David - Walking Away", videoId = "Dbb7xeZGR-U"),
    YoutubeVideo(title = "Craig David - Unbelievable", videoId = "oRGbxfTiEaE"),
    YoutubeVideo(title = "Gold Trap - Mandelbrot Fractal Zoom", videoId = "-5OMHPd6Xpc"),
).shuffled()

// King Arthur - Legend of The Sword is just super epic movie.
val otherEpicMomentsList = listOf(
    YoutubeVideo(title = "Astartes Project by Syama Pedersen", videoId = "O7hgjuFfn3A"),
    YoutubeVideo(title = "King Arthur - Opening Scene FHD - Giant Elephant", videoId = "cRIbbxdGATs"),
    YoutubeVideo(title = "King Arthur - All Powers from King Arthur: Legend of the Sword", videoId = "_nQqIxdsI0o"),
    YoutubeVideo(title = "Rocky Vs Garuda - KGF Chapter 1", videoId = "LecLq_-OpTU"),
    YoutubeVideo(title = "The Statue Reveal - KGF Chapter 1", videoId = "HsXpoTM2N8o"),
    YoutubeVideo(title = "Arcane: League of Legends - Powder's Monkey Bomb Explodes", videoId = "Tz1THyAhx8E"),
    YoutubeVideo(title = "Love, Death & Robots - Season 3 Episode 9 - JIBARO", videoId = "w140SKkoRDw"),
    YoutubeVideo(title = "Love, Death & Robots - Jibaro | Death Dance Opening Scene", videoId = "j6fRCupGH2Q"),
    YoutubeVideo(title = "Bruce Lee - 1965 Color Interview", videoId = "Jv0qjWsXgP8"), // Proof that Bruce is super human or its a frame rate issue
    YoutubeVideo(title = "The One (2001) - Opening fight scene with Jet Li vs Police", videoId = "slqIzuiqPwk"),
    YoutubeVideo(title = "The Matrix Reloaded - Neo vs Smith Clones [Part 2]", videoId = "UvLQMMaVmzU"),
    YoutubeVideo(title = "Kingsglaive: Final Fantasy XV - Nyx vs. Glauca. The Final Battle", videoId = "UVD7W7LvaQY"),
    YoutubeVideo(title = "Kingsglaive: Final Fantasy XV - Battle Scene", videoId = "_58xdeWpeI4"),
    YoutubeVideo(title = "Final Fantasy VII - Advent Children (2006) - Motorcycle Chase Scene", videoId = "y8MU0juAUUg"),
    YoutubeVideo(title = "Final Fantasy Vll - Advent Children (2006) - Motorcycle Fight Scene", videoId = "B5LGDda3qC4"),
    YoutubeVideo(title = "Kung-Fu Hustle (2004) - Kung-fu Masters vs The Beast", videoId = "XoTVze2vzkI"),
    YoutubeVideo(title = "Kung Fu Hustle (2004) - Fight Scene 3 Masters vs The Harpists", videoId = "r8MbVjzgonA"),
    YoutubeVideo(title = "Kung Fu Hustle (2004) - The Landlady and the Landlord vs the Beast", videoId = "tiFKml1IKII"),
    YoutubeVideo(title = "The Incredibles - Kronos Unveiled", videoId = "Y8DMYj94Pi4"),
    ).shuffled()
