package com.singularitycoder.viewmodelstuff2.helpers.constants

import com.singularitycoder.viewmodelstuff2.more.model.YoutubeVideo

val animeFightsList = listOf(
    YoutubeVideo(title = "Shingeki No Kyojin - Eren Rage Mode (Berserk) vs Annie Episode 25", videoId = "w-QxK1I7Va8"),
    YoutubeVideo(title = "Shingeki no Kyojin HD (EPISODE 24) - Eren Titan Transformation vs Annie Scene", videoId = "GLff3_jPZIM"),
    YoutubeVideo(title = "Fog Hill of the Five Elements", videoId = "0OoKXPUvVbo"),
    YoutubeVideo(title = "Fog Hill of the Five Elements (BRIDGE FIGHT SCENE)", videoId = "qZZLkmMeGRY"),
    YoutubeVideo(title = "Fog Hill of the Five Elements - Wu Shan Wu Xing", videoId = "l5k8GjTpa9I"),
    YoutubeVideo(title = "Attack on Titan - Eren vs The Armored Titan full fight", videoId = "hyEbggGnT0U"),
    YoutubeVideo(title = "Attack on Titan - Levi vs Kenny Squad - (Full Fight) HD", videoId = "MyJk2YWhfoU"),
    YoutubeVideo(title = "Attack on Titan - Levi vs. The Beast Titan", videoId = "ceQ4nhyuX2k"),
    YoutubeVideo(title = "Attack On Titan - Floch vs ALL (60 fps)", videoId = "hzp1AeiEIMg"),
    YoutubeVideo(title = "Attack On Titan - The true form of Eren's rumbling titan that destroyed world civilization", videoId = "1-WVczhtXTw"),
    YoutubeVideo(title = "Attack On Titan - Eren's first transformation and first fight scenes", videoId = "p2FKMB_sImg"),
    YoutubeVideo(title = "Attack On Titan - Levi vs The Female Titan", videoId = "QMf_Z-Fl7_w"),
    YoutubeVideo(title = "Attack On Titan - Titan Eren vs Female Titan - 60FPS", videoId = "k2u1nTvBYx0"),
    YoutubeVideo(title = "Attack On Titan - Eren vs Warhammer Titan", videoId = "Rv0085ZOIsg"),
    YoutubeVideo(title = "Saber Alter vs Rider - Fate/stay night: Heaven’s Feel lll", videoId = "8W7x_-mMOtU"),
    YoutubeVideo(title = "Saber Alter Excalibur Morgan [4K 60fps]", videoId = "f1JT8z-3cV0"),
    YoutubeVideo(title = "Demon Slayer - Tanjiro Kamado and Tengen Uzui vs Gyutaro", videoId = "IOkz2ld1-Kk"),
    YoutubeVideo(title = "Boruto - Naruto, Sasuke, and Boruto vs Momoshiki", videoId = "CZJBkQQTiCo"),
    YoutubeVideo(title = "Meliodas vs Ten Commandments", videoId = "92Gvvh0UKjk"),
    YoutubeVideo(title = "Parasyte The Maxim - Fights from anime compilation", videoId = "r_JH_oOkhmk"),
    YoutubeVideo(title = "One Punch Man - Saitama vs Genos Fight | One Punch Man (60FPS)", videoId = "km2OPUctni4"),
    YoutubeVideo(title = "One Punch Man - Saitama vs Boros Fight Full HD", videoId = "ErXfj3sbIfU"),
    YoutubeVideo(title = "Code Geass R2 - Final battle between Kallen and Suzaku", videoId = "9Y44LiqBHsw"),
    YoutubeVideo(title = "Mob Psycho 100 - Shimazaki Fight", videoId = "Ar7fHWRMNoE"),
    YoutubeVideo(title = "Mob Psycho 100 - MOB VS Toichiro Final Fight", videoId = "wRG7Er6qlvk"),
    YoutubeVideo(title = "Mob Psycho 100 - Mob vs Koyama Full Fight (60fps)", videoId = "nJlmcQA_dVQ"),
)

val animeMusicList = listOf(
    YoutubeVideo(title = "Gundam Unicorn - 1ST MOV. :BANSHEE", videoId = "BUXh_AQ5xvI"),
    YoutubeVideo(title = "Gundam Unicorn - MAD-NUG", videoId = "ZcLoj0qoe_g"),
    YoutubeVideo(title = "Gundam Unicorn - MOBILE SUIT ＜W-REC MIX＞", videoId = "6Z1e-3dPiTk"),
    YoutubeVideo(title = "Gundam Unicorn - U.C.0096", videoId = "xMMIiuefw8k"),
    YoutubeVideo(title = "Gundam Unicorn - UNICORN", videoId = "hAqqAwhfet8"),
    YoutubeVideo(title = "Gundam Unicorn - MOBILE SUIT", videoId = "afuVyoW15HM"),
    YoutubeVideo(title = "Gundam Unicorn - LAPLACE", videoId = "fWjLln3W2xI"),
    YoutubeVideo(title = "Gundam Unicorn - FULL-FRONTAL", videoId = "xnx2WLiLrDM"),
    YoutubeVideo(title = "Gundam Unicorn - LIFE & DEATH", videoId = "s5UgiiI9u84"),
    YoutubeVideo(title = "Gundam Unicorn - RX-0", videoId = "bokihr6DzIw"),
    YoutubeVideo(title = "Gundam Unicorn - ZERO GRAVITY", videoId = "rq2qiODoKus"),
    YoutubeVideo(title = "Gundam Unicorn - 2ND MOV. :PSYCHO-FIELD", videoId = "9uP_sNt5QGw"),
    YoutubeVideo(title = "Gundam Unicorn - 3RD MOV. :ANGELO", videoId = "E7AqQLhQgdQ"),
    YoutubeVideo(title = "Gundam Unicorn - 5TH MOV. :GUNDAM", videoId = "IbyeO2nkm9I"),
    YoutubeVideo(title = "Gundam Unicorn - 1stMob. :2009522or0311", videoId = "HL78LkCCGcg"),
    YoutubeVideo(title = "Gundam Unicorn - 2ndMob. :MSGUCEP7", videoId = "M5kv6tHHkIQ"),
    YoutubeVideo(title = "Gundam Unicorn - 6thMob. :UNICORN GUNDAM", videoId = "4TgW2Lq9Wv8"),
    YoutubeVideo(title = "Gundam Unicorn - 8thMob. :BEGINNING ＜ORCH-VER＞", videoId = "KyCuNKwxwlo"),
    YoutubeVideo(title = "Sawano Hiroyuki Playlist - Avid, Tranquility, CRY, CRYst-Alise, e of s, ViEW, narrative, ninelie ＜cry-v＞, Binary Star, Unti-L, Cage, 0.vers, oldToday, mot1on, No differences, Till I, scaPEGoat", videoId = "PUSkqc1amgI"),
    YoutubeVideo(title = "Sawano Hiroyuki 2nd Playlist", videoId = "388h287dOWc"),
    YoutubeVideo(title = "Sirius the Jaeger - Definition of Fate", videoId = "3bhJ3DC789g"),
    YoutubeVideo(title = "Sirius the Jaeger - Rare Occasions", videoId = "JdNB9sCQ_fo"),
    YoutubeVideo(title = "Ost Anne Happy - Michino Timothy Kimino Kimochi", videoId = "815kbvmNWNM"),
    YoutubeVideo(title = "Aimer - Am02:00", videoId = "-Hn6O-WvD7o"),
    YoutubeVideo(title = "Aimer - Even Heaven", videoId = "BOGoJYZWmuk"),
    YoutubeVideo(title = "Aimer - Re I Am", videoId = "YyZdbDEgK50"),
    YoutubeVideo(title = "Aimer - StarRingChild", videoId = "cmXW3qfhT60"),
    YoutubeVideo(title = "Aimer - Higher Ground", videoId = "w_FeX0Z8JAo"),
    YoutubeVideo(title = "Aimer - Kyoukara Omoide", videoId = "ImRjy0vgYoI"),
    YoutubeVideo(title = "Aimer - Kataomoi(Unrequited Love)", videoId = "F_62fr-I3E4"),
    YoutubeVideo(title = "Attack on Titan - Best of Soundtracks", videoId = "ZUj6k5LQrJ0"),
    YoutubeVideo(title = "Attack on Titan - Reiner and Bertholdt's Transformation Theme", videoId = "rdml5r6Y_g4"),
    YoutubeVideo(title = "The Seven Deadly Sins - Here Comes The Jikkai · KOHTA YAMAMOTO", videoId = "VMZTkvnRUPE"),
    YoutubeVideo(title = "Berserk - Son Cauchemar - Shiro Sagisu", videoId = "FNC-M9279jE"),
    YoutubeVideo(title = "Berserk Golden Age - Hundred Years War", videoId = "OG8GxzJTBck"),
    YoutubeVideo(title = "Kenji Kawai Cinema Symphony Ghost In The Shell", videoId = "WjOuEruzoh0"),
    YoutubeVideo(title = "Made In Abyss - Tomorrow", videoId = "BeSbmS06k1k"),
    YoutubeVideo(title = "Tower of God - Irregular God", videoId = "ENCJrayjnjE"),
    YoutubeVideo(title = "Tower of God - Alita", videoId = "elGoXAIsddM"),
    YoutubeVideo(title = "Tower of God - Berserker Bam", videoId = "BNZerdoRl_Q"),
    YoutubeVideo(title = "Megalo Box - MEGALOBOX", videoId = "Pxg9s9OD-qU"),
    YoutubeVideo(title = "Megalo Box - Enter The Arena", videoId = "rqUCKw13D0Y"),
    YoutubeVideo(title = "Uchouten Kazoku - Kakusanakute mo li ja nai ka", videoId = "thiLdlj0Oqk"),
    YoutubeVideo(title = "Uchouten Kazoku - Suibun Okiniiri no You desu", videoId = "RJFwlHyGAsc"),
    YoutubeVideo(title = "Uchouten Kazoku - Ebisugawa no Musume, Kaisei", videoId = "xplxAEr0xG0"),
    YoutubeVideo(title = "Uchouten Kazoku - Hodo Hodo no Eikou are", videoId = "mIjOgDMpMkU"),
    YoutubeVideo(title = "Uchouten Kazoku - Que Sera Sera (TV Size)", videoId = "9v2DACnQ7KE"),
)

val epicAnimeMomentsList = listOf(
    YoutubeVideo(title = "Code Geass, Best Anime Ever, Ending! 1080p", videoId = "rS-FBuWG_zQ"),
    YoutubeVideo(title = "Code Geass R2 - Lelouch Takes Over the World", videoId = "xnFdY7168DY"),
    YoutubeVideo(title = "Attack On Titan - Eren vs Annie - Eren Transforms in the forest", videoId = "BPohSG4ZNes"),
    YoutubeVideo(title = "Attack on Titan - The Owl", videoId = "gLtky3DaBO0"),
    YoutubeVideo(title = "Attack on Titan - Colossal & Armored Titan REVEALED", videoId = "3v_561hRxs4"),
    YoutubeVideo(title = "Attack on Titan - Annie Leonhardt/Female Titan - Powers & Fight Scenes (AOT)", videoId = "IZdNJJueKfU"),
    YoutubeVideo(title = "Kizumonogatari Part 2: Nekketsu - Koyomi Araragi vs. Guillotine Cutter", videoId = "yl7ldmQPwIM"),
    YoutubeVideo(title = "The Rumbling Begins - Attack on Titan Season 4 Episode 5", videoId = "Uwza8rHaPzw"),
    YoutubeVideo(title = "Shingeki no Kyojin - Eren blocks gate with boulder", videoId = "iaLJ1Jk35lU"),
    YoutubeVideo(title = "Shingeki no Kyojin - Eren Transforms - Willy Tybur Speech: The Final Season", videoId = "pR3KdTbbBoM"),
    YoutubeVideo(title = "Monster - Tenma confronts Johan", videoId = "NMZVAN3UUmg"),
)

val otherMusicList = listOf(
    YoutubeVideo(title = "Pandit Jasraj - Vraje Vasantam", videoId = "ItAnTZjopAM"),
    YoutubeVideo(title = "James Brown - I Got The Feelin' (Extended Version)", videoId = "Cda0twzCMC4"),
    YoutubeVideo(title = "James Brown - People Get Up And Drive Your Funky Soul (Remix)", videoId = "Nl-RVIdTUVI"),
    YoutubeVideo(title = "James Brown - Ain't It Funky Now (Live At The Olympia, Paris / 1971)", videoId = "NKloz_wR6n4"),
    YoutubeVideo(title = "James Brown - Sunny (Live At The Olympia, Paris / 1971)", videoId = "cNFb7vfANVE"),
    YoutubeVideo(title = "James Brown - Get Up Offa That Thing (Release The Pressure)", videoId = "QS8FxHsw0U0"),
    YoutubeVideo(title = "James Brown - Papa Don't Take No Mess", videoId = "T0QQUps8954"),
    YoutubeVideo(title = "James Brown - Mind Power", videoId = "7naR12OPxRw"),
    YoutubeVideo(title = "James Brown - Super Bad, Pts. 1, 2 & 3 (Mono Version)", videoId = "u4ePdvrp9go"),
    YoutubeVideo(title = "James Brown - The Payback", videoId = "D7ks03zsg1o"),
    YoutubeVideo(title = "James Brown - Cold Sweat", videoId = "lSh-QQuW3lU"),
    YoutubeVideo(title = "James Brown - Papa's Got A Brand New Bag", videoId = "M7DNkovC2Tk"),
    YoutubeVideo(title = "James Brown - Your Cheatin' Heart", videoId = "fGY9i61XhEg"),
    YoutubeVideo(title = "James Brown - Money Won't Change You", videoId = "8tJ6HyUmjqk"),
    YoutubeVideo(title = "James Brown - Get It Together (Boston) 1968", videoId = "RnO8sHmkbv4"),
    YoutubeVideo(title = "James Brown - I Got The Feeling - Live At The Boston Garden (1968)", videoId = "n0rOo8bX6P8"),
    YoutubeVideo(title = "James Brown - Gonna Have A Funky Good Time", videoId = "P6iSL1dsShc"),
    YoutubeVideo(title = "Lamb of God - Walk with Me In Hell", videoId = "m4QyQk8vOCY"),
    YoutubeVideo(title = "Lamb of God - Ashes of the Wake", videoId = "PJcy3VQJA6o"),
    YoutubeVideo(title = "Lamb of God - Omerta", videoId = "-xYZM04JxnQ"),
    YoutubeVideo(title = "Lamb of God - The Faded Line", videoId = "JuRRnVqv2Vc"),
    YoutubeVideo(title = "Lamb of God - 11th Hour", videoId = "beltaLLilj4"),
    YoutubeVideo(title = "Lamb of God - Descending", videoId = "_V_ZbJE5oLs"),
    YoutubeVideo(title = "Lamb of God - Blacken the Cursed Sun", videoId = "_oGY68hJbs4"),
    YoutubeVideo(title = "Lamb of God - As the Palaces Burn", videoId = "eWVrdFrpXHE"),
    YoutubeVideo(title = "Louis Armstrong - What A Wonderful World (Lyrics)", videoId = "A3yCcXgbKrE"),
    YoutubeVideo(title = "Coldplay - Up&Up", videoId = "BPNTC7uZYrI"),
    YoutubeVideo(title = "Coldplay - The Scientist", videoId = "RB-RcX5DS5A"),
    YoutubeVideo(title = "GN Balasubramaniam - Manasu Swadhina", videoId = "IA5Oa6VJAyk"),
    YoutubeVideo(title = "TM Krishna - Ragam Neelambari", videoId = "ovgWK5aQcpM"),
    YoutubeVideo(title = "TM Krishna - Manavyalakinchara, Tyagaraja Smaranotsava Sabha Nellore", videoId = "ovgWK5aQcpM"),
    YoutubeVideo(title = "TM Krishna - Ragam Nalinakanthi", videoId = "5yZEsJDJ9yc")
)
